// Mamlakat nomi -> bayroq emoji. WC2026 ishtirokchi 48 jamoa uchun.
const FLAGS: Record<string, string> = {
  Mexico: "🇲🇽",
  "United States": "🇺🇸",
  USA: "🇺🇸",
  Canada: "🇨🇦",
  "South Africa": "🇿🇦",
  Jamaica: "🇯🇲",
  Argentina: "🇦🇷",
  Brazil: "🇧🇷",
  Uruguay: "🇺🇾",
  Colombia: "🇨🇴",
  Ecuador: "🇪🇨",
  Paraguay: "🇵🇾",
  Venezuela: "🇻🇪",
  Bolivia: "🇧🇴",
  Chile: "🇨🇱",
  Peru: "🇵🇪",
  France: "🇫🇷",
  Spain: "🇪🇸",
  Germany: "🇩🇪",
  Portugal: "🇵🇹",
  England: "🏴",
  Italy: "🇮🇹",
  Netherlands: "🇳🇱",
  Belgium: "🇧🇪",
  Croatia: "🇭🇷",
  Switzerland: "🇨🇭",
  Austria: "🇦🇹",
  Denmark: "🇩🇰",
  Norway: "🇳🇴",
  Sweden: "🇸🇪",
  Finland: "🇫🇮",
  Iceland: "🇮🇸",
  Ireland: "🇮🇪",
  "Northern Ireland": "🇬🇧",
  "Bosnia & Herzegovina": "🇧🇦",
  "Bosnia and Herzegovina": "🇧🇦",
  "Cape Verde": "🇨🇻",
  Albania: "🇦🇱",
  Bulgaria: "🇧🇬",
  Slovenia: "🇸🇮",
  "North Macedonia": "🇲🇰",
  Russia: "🇷🇺",
  Belarus: "🇧🇾",
  Estonia: "🇪🇪",
  Latvia: "🇱🇻",
  Lithuania: "🇱🇹",
  Israel: "🇮🇱",
  Lebanon: "🇱🇧",
  Scotland: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  Wales: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  Poland: "🇵🇱",
  Turkey: "🇹🇷",
  Ukraine: "🇺🇦",
  "Czech Republic": "🇨🇿",
  Hungary: "🇭🇺",
  Serbia: "🇷🇸",
  Slovakia: "🇸🇰",
  Romania: "🇷🇴",
  Greece: "🇬🇷",
  "Saudi Arabia": "🇸🇦",
  Iran: "🇮🇷",
  Iraq: "🇮🇶",
  Qatar: "🇶🇦",
  UAE: "🇦🇪",
  Jordan: "🇯🇴",
  "South Korea": "🇰🇷",
  Japan: "🇯🇵",
  Australia: "🇦🇺",
  "New Zealand": "🇳🇿",
  Uzbekistan: "🇺🇿",
  Senegal: "🇸🇳",
  Morocco: "🇲🇦",
  Tunisia: "🇹🇳",
  Algeria: "🇩🇿",
  Egypt: "🇪🇬",
  Ghana: "🇬🇭",
  Nigeria: "🇳🇬",
  "Ivory Coast": "🇨🇮",
  Cameroon: "🇨🇲",
  "DR Congo": "🇨🇩",
  Mali: "🇲🇱",
  Panama: "🇵🇦",
  "Costa Rica": "🇨🇷",
  Honduras: "🇭🇳",
  Haiti: "🇭🇹",
  "Curaçao": "🇨🇼",
};

// Knockout placeholder: "W77" (winner of match 77), "L101" (loser),
// "1A"/"2B" (1-/2-o'rin), "3A/B/C/D" (3-o'rinlilar) — bularning bayrog'i bo'lmaydi.
const PLACEHOLDER_RE = /^([WLwl]\d+|[123][A-L]([/][A-L])*)$/;

export function isPlaceholderTeam(team: string): boolean {
  return PLACEHOLDER_RE.test(team.trim());
}

export function flagFor(team: string): string {
  if (FLAGS[team]) return FLAGS[team];
  if (isPlaceholderTeam(team)) return "❓";
  return "⚽";
}
