// Mamlakat nomi -> bayroq emoji. WC2026 ishtirokchi 48 jamoa uchun.
const FLAGS: Record<string, string> = {
  Mexico: "🇲🇽",
  "United States": "🇺🇸",
  USA: "🇺🇸",
  Canada: "🇨🇦",
  "South Africa": "🇿🇦",
  Jamaica: "🇯🇲",
  Argentina: "🇦🇷",
  Brazil: "🇧🇷",
  Uruguay: "🇺🇾",
  Colombia: "🇨🇴",
  Ecuador: "🇪🇨",
  Paraguay: "🇵🇾",
  Venezuela: "🇻🇪",
  Bolivia: "🇧🇴",
  Chile: "🇨🇱",
  Peru: "🇵🇪",
  France: "🇫🇷",
  Spain: "🇪🇸",
  Germany: "🇩🇪",
  Portugal: "🇵🇹",
  England: "🏴",
  Italy: "🇮🇹",
  Netherlands: "🇳🇱",
  Belgium: "🇧🇪",
  Croatia: "🇭🇷",
  Switzerland: "🇨🇭",
  Austria: "🇦🇹",
  Denmark: "🇩🇰",
  Norway: "🇳🇴",
  Scotland: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  Wales: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  Poland: "🇵🇱",
  Turkey: "🇹🇷",
  Ukraine: "🇺🇦",
  "Czech Republic": "🇨🇿",
  Hungary: "🇭🇺",
  Serbia: "🇷🇸",
  Slovakia: "🇸🇰",
  Romania: "🇷🇴",
  Greece: "🇬🇷",
  "Saudi Arabia": "🇸🇦",
  Iran: "🇮🇷",
  Iraq: "🇮🇶",
  Qatar: "🇶🇦",
  UAE: "🇦🇪",
  Jordan: "🇯🇴",
  "South Korea": "🇰🇷",
  Japan: "🇯🇵",
  Australia: "🇦🇺",
  "New Zealand": "🇳🇿",
  Uzbekistan: "🇺🇿",
  Senegal: "🇸🇳",
  Morocco: "🇲🇦",
  Tunisia: "🇹🇳",
  Algeria: "🇩🇿",
  Egypt: "🇪🇬",
  Ghana: "🇬🇭",
  Nigeria: "🇳🇬",
  "Ivory Coast": "🇨🇮",
  Cameroon: "🇨🇲",
  "DR Congo": "🇨🇩",
  Mali: "🇲🇱",
  Panama: "🇵🇦",
  "Costa Rica": "🇨🇷",
  Honduras: "🇭🇳",
  Haiti: "🇭🇹",
  "Curaçao": "🇨🇼",
};

export function flagFor(team: string): string {
  return FLAGS[team] ?? "⚽";
}
